export enum SchedulingStatus {
  AGENDADO = 'AGENDADO',
  EXAMES_REALIZADOS = 'EXAMES_REALIZADOS',
  AGUARDANDO_RESULTADOS = 'AGUARDANDO_RESULTADOS',
  AGUARDANDO_PARECER_MÉDICO = 'AGUARDANDO_PARECER_MÉDICO',
  CANCELADO = 'CANCELADO',
  FINALIZADO = 'FINALIZADO',
}
