version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local
